export const skillData = [
    {
        skillName: "JavaScript",
        Image: "/JavaScriptIcon.png",
        width: 80,
        height: 80,
    },
    {
        skillName: "HTML",
        Image: "/HTMLIcon.png",
        width: 80,
        height: 80,
    },
    {
        skillName: "CSS",
        Image: "/CSSIcon.png",
        width: 80,
        height: 80,
    },
    {
        skillName: "React",
        Image: "/ReactIcon.png",
        width: 80,
        height: 80,
    },
    {
        skillName: "Redux",
        Image: "/ReduxIcon.png",
        width: 80,
        height: 80,
    },
    {
        skillName: "Axios",
        Image: "/AxiosIcon.png",
        width: 80,
        height: 80,
    },
    {
        skillName: "Firebase",
        Image: "/FirebaseIcon.png",
        width: 80,
        height: 80,
    },
    {
        skillName: "GitHub",
        Image: "/GitHubIcon.png",
        width: 80,
        height: 80,
    },
    {
        skillName: "Git",
        Image: "/GitIcon.png",
        width: 80,
        height: 80,
    },
    {
        skillName: "Netlify",
        Image: "/NetlifyIcon.png",
        width: 80,
        height: 80,
    },
    {
        skillName: "OpenSource",
        Image: "/OpenSourceIcon.png",
        width: 80,
        height: 80,
    },
    {
        skillName: "Vite",
        Image: "/ViteIcon.png",
        width: 80,
        height: 80,
    },
    {
        skillName: "Vercel",
        Image: "/VercelIcon.png",
        width: 80,
        height: 80,
    },
    {
        skillName: "Yarn",
        Image: "/YarnIcon.png",
        width: 80,
        height: 80,
    },
    {
        skillName: "VSCode",
        Image: "/VSCodeIcon.png",
        width: 80,
        height: 80,
    },
    {
        skillName: "npm",
        Image: "/npmIcon.png",
        width: 80,
        height: 80,
    },
    {
        skillName: "BootStrap",
        Image: "/BootstrapIcon.png",
        width: 80,
        height: 80,
    },
    {
        skillName: "Tailwind",
        Image: "/Tailwind.png",
        width: 80,
        height: 80,
    },
    {
        skillName: "FramerMotion",
        Image: "/FramerMotion.png",
        width: 80,
        height: 80,
    },
    {
        skillName: "Next.js",
        Image: "/NextJS.png",
        width: 80,
        height: 80,
    },
    {
        skillName: "TypeScript",
        Image: "/TypeScript.png",
        width: 80,
        height: 80,
    },

]